# Generated by Django 6.0.5 on 2026-06-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_requested_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('Not Requested', 'Not Requested'), ('Requested', 'Requested'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Not Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payment Done', 'Payment Done'), ('Confirmed', 'Confirmed'), ('Travel Scheduled', 'Travel Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refund Processing', 'Refund Processing'), ('Refund Completed', 'Refund Completed')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='package',
            name='tags',
            field=models.CharField(max_length=255),
        ),
    ]
